#!/usr/bin/env python3

"""

Step04_Zero

Authors: Ryan Howard (@RJKH1994) & Matt Bridge (@MWBRIDGE)

- The purpose of this code is to zero (translate) team-level GPS tracking data so that the pitch origin aligns to (0, 0) in the coordinate system.
- The code will iterate through every folder inside MASTER_FOLDER. Each subfolder is treated as an individual Root_folder (i.e., an individual game).
- Within each root_folder, there should be an Output folder containing:
    - Pitch_Lengths.csv (pitch metadata including origin and dimensions)
    - Phase-level team tracking files ending with *_GPS_Data_new_10Hz_filled.csv
    
- The pipeline for the workflow in each root_folder is to:
    1) Read pitch origin and dimensions from Pitch_Lengths.csv.
    2) Identify player position columns (_x and _y) in each tracking file.
    3) Subtract the pitch origin (Opitch_x, Opitch_y) so all coordinates are zero-referenced.
    4) Optionally clamp coordinates to pitch bounds.
    5) Save new files prefixed with Zeroed_ alongside the originals.

Inputs (per Root_folder/game):
- Output/Pitch_Lengths.csv
    - Must contain pitch origin and dimensions (Opitch_x, Opitch_y, pitch_length, pitch_width)
- Output/*_GPS_Data_new_10Hz_filled.csv
    - First column is Time
    - Remaining columns are player coordinates (<PLAYER>_x, <PLAYER>_y)

Outputs (per Root_folder/game):
- Output/Zeroed_*_GPS_Data_new_10Hz_filled.csv
    - Same structure as input files, with coordinates translated to a (0, 0) pitch origin

Notes:
- Zeroing is performed using pitch metadata generated by the pitch normalisation script.
- If pitch origin metadata are missing, a fallback based on global minima is used (less reliable).
- Optional clamping ensures coordinates remain within pitch bounds but can be disabled.
- Original files are never overwritten to preserve reproducibility.

"""

import os
import re
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd


# CONFIGURATION #

MASTER_FOLDER = '/Users/ryanhoward/Desktop/Data' # Change this to the master folder containing individual game folders

NEG_TOL = 1e-6
CLAMP_TO_PITCH_BOUNDS = True

INPUT_SUFFIX = '_GPS_Data_new_10Hz_filled.csv'
PITCH_META_FILENAME = 'Pitch_Lengths.csv'
OUTPUT_FOLDER_NAME = 'Output'


# FUNCTIONS #

## Read pitch metadata

# FUNCTION 1: Read pitch origin and dimensions from Pitch_Lengths.csv

def read_pitch_meta(output_dir: str) -> Tuple[Optional[float], Optional[float], Optional[float], Optional[float], Optional[int]]:
    """
    Read pitch origin, dimensions, and axis swap flag from Pitch_Lengths.csv.

    Returns:
    - ox, oy: pitch origin coordinates
    - length, width: pitch dimensions in metres
    - switch_xy: flag indicating whether axes were swapped upstream (0/1)
    """
    path = os.path.join(output_dir, PITCH_META_FILENAME)
    if not os.path.exists(path):
        print("Pitch_Lengths.csv not found in:", output_dir)
        return None, None, None, None, None

    df = pd.read_csv(path)
    if df.empty:
        print("Pitch_Lengths.csv is empty:", path)
        return None, None, None, None, None

    cols = {str(c).lower().strip(): c for c in df.columns}

    def getf(*names):
        for name in names:
            key = str(name).lower().strip()
            if key in cols:
                try:
                    v = df.iloc[0][cols[key]]
                    if pd.isna(v):
                        continue
                    return float(v)
                except Exception:
                    continue
        return None

    def geti(*names):
        for name in names:
            key = str(name).lower().strip()
            if key in cols:
                try:
                    v = df.iloc[0][cols[key]]
                    if pd.isna(v):
                        continue
                    return int(v)
                except Exception:
                    continue
        return None

    ox = getf('origin_x', 'opitch_x', 'opitchx')
    oy = getf('origin_y', 'opitch_y', 'opitchy')

    length = getf('length', 'pitch_length', 'pitchlength')
    width  = getf('width', 'pitch_width', 'pitchwidth')

    switch_xy = geti('switch_xy')

    return ox, oy, length, width, switch_xy


## Detect player position columns

# FUNCTION 2: Identify player X/Y coordinate columns

def detect_pos_cols(df: pd.DataFrame) -> Tuple[List[str], List[str]]:
    """
    Identify player position columns ending with _x and _y.

    Excludes:
    - pitch metadata columns
    - origin columns
    - velocity / acceleration derived variables
    """
    x_cols, y_cols = [], []
    for c in df.columns:
        cl = str(c).lower()
        if not re.search(r'_(x|y)$', cl):
            continue
        if any(cl.startswith(p) for p in ['pitch_', 'origin_', 'opitch_']):
            continue
        if any(tok in cl for tok in ['vel', 'velocity', 'acc', 'accel', 'speed']):
            continue
        if cl.endswith('_x'):
            x_cols.append(c)
        elif cl.endswith('_y'):
            y_cols.append(c)

    def stem(name): 
        return str(name)[:-2]

    x_cols = sorted(x_cols, key=stem)
    y_cols = sorted(y_cols, key=stem)
    return x_cols, y_cols


# FUNCTION 3: Coerce position columns to numeric

def to_numeric(df: pd.DataFrame, cols: List[str]) -> None:
    """Convert specified columns to numeric, coercing invalid values to NaN."""
    for c in cols:
        df[c] = pd.to_numeric(df[c], errors='coerce')


## Core operations

# FUNCTION 4: Subtract pitch origin

def subtract_origin(df: pd.DataFrame,
                    x_cols: List[str],
                    y_cols: List[str],
                    ox: Optional[float],
                    oy: Optional[float]) -> None:
    """
    Translate coordinates so that the pitch origin aligns to (0, 0).

    If ox/oy are missing, falls back to shifting by global minima.
    """
    if ox is None or oy is None:
        print("Warning: Opitch_x/Opitch_y missing. Falling back to global minima shifting.")

    if ox is not None:
        for c in x_cols:
            df[c] = df[c] - ox
    else:
        xmin = pd.concat([df[c] for c in x_cols]).min(skipna=True) if x_cols else 0.0
        if pd.notna(xmin):
            for c in x_cols:
                df[c] = df[c] - xmin

    if oy is not None:
        for c in y_cols:
            df[c] = df[c] - oy
    else:
        ymin = pd.concat([df[c] for c in y_cols]).min(skipna=True) if y_cols else 0.0
        if pd.notna(ymin):
            for c in y_cols:
                df[c] = df[c] - ymin


# FUNCTION 5: Clamp values and report out-of-bounds statistics

def clamp_and_report(df: pd.DataFrame,
                     x_cols: List[str],
                     y_cols: List[str],
                     length: Optional[float],
                     width: Optional[float],
                     fname: str,
                     clamp_to_bounds: bool) -> None:
    """
    Clamp small numerical negatives to zero, optionally clamp to pitch bounds, and report out-of-bounds counts and percentages prior to clamping. This is important to check and report post-run.
    """
    total_x = sum(df[c].notna().sum() for c in x_cols)
    total_y = sum(df[c].notna().sum() for c in y_cols)

    oob_x = 0
    oob_y = 0

    if length is not None and x_cols:
        for c in x_cols:
            s = pd.to_numeric(df[c], errors='coerce')
            oob_x += int(((s < -NEG_TOL) | (s > length + NEG_TOL)).sum())

    if width is not None and y_cols:
        for c in y_cols:
            s = pd.to_numeric(df[c], errors='coerce')
            oob_y += int(((s < -NEG_TOL) | (s > width + NEG_TOL)).sum())

    pct_oob_x = 100.0 * oob_x / total_x if total_x > 0 else 0.0
    pct_oob_y = 100.0 * oob_y / total_y if total_y > 0 else 0.0

    for c in x_cols + y_cols:
        s = pd.to_numeric(df[c], errors='coerce').to_numpy()
        s = np.where(s < -NEG_TOL, 0.0, s)
        df[c] = s

    if clamp_to_bounds and length is not None:
        for c in x_cols:
            df[c] = np.clip(pd.to_numeric(df[c], errors='coerce'), 0.0, length)

    if clamp_to_bounds and width is not None:
        for c in y_cols:
            df[c] = np.clip(pd.to_numeric(df[c], errors='coerce'), 0.0, width)

    xmin = float(pd.concat([df[c] for c in x_cols]).min(skipna=True)) if x_cols else float("nan")
    xmax = float(pd.concat([df[c] for c in x_cols]).max(skipna=True)) if x_cols else float("nan")
    ymin = float(pd.concat([df[c] for c in y_cols]).min(skipna=True)) if y_cols else float("nan")
    ymax = float(pd.concat([df[c] for c in y_cols]).max(skipna=True)) if y_cols else float("nan")

    print(
        f"   [{fname}] post-fix ranges: X[{xmin:.3f},{xmax:.3f}] "
        f"Y[{ymin:.3f},{ymax:.3f}] | "
        f"OOB pre-clamp: x={oob_x}/{total_x} ({pct_oob_x:.2f}%), "
        f"y={oob_y}/{total_y} ({pct_oob_y:.2f}%)"
    )


## File processing

# FUNCTION 6: Process a single tracking file

def process_file(path: str,
                 ox: Optional[float],
                 oy: Optional[float],
                 length: Optional[float],
                 width: Optional[float],
                 clamp_to_bounds: bool) -> None:
    df = pd.read_csv(path)
    x_cols, y_cols = detect_pos_cols(df)

    if not x_cols or not y_cols:
        print(f"{os.path.basename(path)}: No position columns detected.")
        return

    to_numeric(df, x_cols + y_cols)

    subtract_origin(df, x_cols, y_cols, ox, oy)
    clamp_and_report(df, x_cols, y_cols, length, width, os.path.basename(path), clamp_to_bounds)

    out_name = f"Zeroed_{os.path.basename(path)}"
    out_path = os.path.join(os.path.dirname(path), out_name)
    df.to_csv(out_path, index=False)
    print(f"Saved {out_name}")


## Root folder iteration

# FUNCTION 7: Identify valid Root_folders

def iter_root_folders(master_folder: str) -> List[str]:
    """
    Treat each immediate subfolder as a Root_folder if it contains an Output folder.
    """
    roots = []
    for name in sorted(os.listdir(master_folder)):
        p = os.path.join(master_folder, name)
        if not os.path.isdir(p):
            continue
        if os.path.isdir(os.path.join(p, OUTPUT_FOLDER_NAME)):
            roots.append(p)
    return roots


## Run one root folder

# FUNCTION 8: Process a single Root_folder

def process_root_folder(root_folder: str) -> None:
    output_dir = os.path.join(root_folder, OUTPUT_FOLDER_NAME)

    print("\n" + "=" * 70)
    print(f"Root:   {root_folder}")
    print(f"Output: {output_dir}")

    ox, oy, length, width, switch_xy = read_pitch_meta(output_dir)
    print(f"Meta: origin=({ox}, {oy})  pitch=({length} × {width})  switch_xy={switch_xy}")

    clamp_to_bounds = CLAMP_TO_PITCH_BOUNDS
    if length is None or width is None:
        print("Warning: pitch_length/pitch_width missing. Clamping disabled for this root.")
        clamp_to_bounds = False

    file_paths = [
        os.path.join(output_dir, f)
        for f in os.listdir(output_dir)
        if f.endswith(INPUT_SUFFIX)
        and not f.startswith('Zeroed_')
        and not f.startswith('Processed_')
    ]

    if not file_paths:
        print(f"No files ending '{INPUT_SUFFIX}' found.")
        return

    print(f"Found {len(file_paths)} files for zeroing.")
    for path in sorted(file_paths):
        print(f"Processing {os.path.basename(path)}")
        try:
            process_file(path, ox, oy, length, width, clamp_to_bounds)
        except Exception as e:
            print(f"{os.path.basename(path)}: ERROR -> {e}")


# MAIN WORKFLOW #

def main():
    if not os.path.isdir(MASTER_FOLDER):
        raise FileNotFoundError(f"MASTER_FOLDER not found: {MASTER_FOLDER}")

    roots = iter_root_folders(MASTER_FOLDER)
    if not roots:
        print(f"No root folders with '{OUTPUT_FOLDER_NAME}' found in:\n  {MASTER_FOLDER}")
        return

    print(f"Found {len(roots)} root folder(s).")
    for rf in roots:
        process_root_folder(rf)

    print("\nAll folders processed.")


if __name__ == "__main__":
    main()
